name: Build & Push Backend Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t ayush272002/rightful-backend:latest .
          docker push ayush272002/rightful-backend:latest

      - name: Verify backend image by pulling
        run: |
          docker pull ayush272002/rightful-backend:latest
          docker images | grep ayush272002/rightful-backend

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop backend || true
            sudo docker rm backend || true
            sudo docker system prune -af
            sudo docker volume prune -f
            sudo docker pull ayush272002/rightful-backend:latest
            sudo docker run -d \
              --name backend \
              -p 8000:8000 \
              -e PORT=8000 \
              -e INFURA_PROJECT_ID="${{ secrets.INFURA_PROJECT_ID }}" \
              -e CONTRACT_ADDRESS="${{ secrets.CONTRACT_ADDRESS }}" \
              -e PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" \
              -e GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
              ayush272002/rightful-backend:latest
