name: Build & Push Backend Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/rightful-backend:latest" >> $GITHUB_ENV

      - name: Build Docker image from ./backend
        run: |
          cd backend
          docker build -t $IMAGE .

      - name: Push Docker image
        run: docker push $IMAGE
